# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39178b05838f69d3f4bfcdf72e9aa36f1740cf1cf71b2f6260b1612d729c08c2b94ddf6ac3e997e1c6e933adbe3ab09eaac3b2ec9b1328b3cc03ede759c0b5d8

test:
  secret_key_base: 331b3bd762eb428d60dcd041458e1cd3aa900db8eeda6d4185801bf3df3aefa70d27c7a0cbe8b2c39dc50b5960aeeb378f27ca46b4165faa13bdb0f51d416ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
